---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-app
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "changeme"
        - name: MYSQL_DATABASE
          value: "syseleven"
        - name: MYSQL_USER
          value: "shopware"
        - name: MYSQL_PASSWORD
          value: "changeme"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data
