apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: metakube-all
  namespace: default
spec:
  commonName: '*.<YOUR_NAME>.plgrnd.be'
  dnsNames:
    - '*.<YOUR_NAME>.plgrnd.be'
  secretName: metakube-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
